commands_list = ['lf', 'ldir', 'pwd', 'cd', 'manual', 'mkdir',
                 'calendar', 'calc', 'whoami', 'echo', 'rm',
                 'cat', 'cp', 'mv', 'date', 'file', 'history',
                 'head', 'tail', 'touch', 'wc', 'ip', 'host', 'arch', 'ps', 'wget', 'kill', 'diff', 'chmod', 'grep', 
                 'tree']

commands_list_manual = {
    'exit': "Exits the shell where it is currently running. \nusage: 'exit'",
    'clear': "Clears the terminal screen. \nusage: 'clear'",
    'lf': "Lists all files in the current directory. \nusage: 'lf [DIRECTORY]...'",
    'ldir': "Lists all directories in the current directory. \nusage: 'ldir [DIRECTORY]...'",
    'pwd': "Prints the name of the current/working directory. \nusage: 'pwd'",
    'cd': "Changes the current/working directory. \nusage: 'cd [DIRECTORY]'",
    'manual': "Gives information about a command. \nusage: 'manual [COMMAND] \nFor example: manual pwd'",
    'mkdir': 'Make directories - used for creating directories if they do not already exist. \nusage: mkdir [DIRECTORY_NAME]...',
    'calendar': "Displays the calendar of a given date. \nusage: 'calendar [YEAR]' or 'calendar [YEAR] [MONTH]' \nFor example: 'calendar 2021' or 'calendar 2021 12'",
    'calc': "Evaluates a mathematical expression. \nusage: 'calc [EXPR]'",
    'whoami': "Displays the username of the currently logged-in user. \nusage: 'whoami'",
    'echo': "Displays a line of text. \nusage: 'echo [TEXT]'",
    'rm': "Remove files or directories. \nusage: 'rm [DIRECTORY]' or 'rm [FILE]'",
    'cat': "Concatenate files and print on the standard output. \nusage: 'cat [FILE]...'",
    'cp': "Copy files from source to destination. \nDestination file is created if it doesn't already exist. \nusage: 'cp [SOURCE_FILE] [DESTINATION_FILE]' or 'cp [SOURCE_FILE] [DESTINATION_DIRECTORY]'",
    'mv': "Move files from source to destination. \nIf destination file doesn't exist, then source file is renamed to destination file's name. \nIf destination file exists, then contents of source file are copied to destination file and source file is deleted. \n"
    "usage: 'mv [SOURCE_FILE] [DESTINATION_FILE]' or 'mv [SOURCE_FILE] [DESTINATION_DIRECTORY]'",
    'date': "Displays the current date and time. \nusage: 'date'",
    'file': "Determines and displays the file type and other details. \n usage: 'file [FILE]...'",
    'history': "Displays the history of the executed commands. \nusage: 'history' - for viewing the local history of the shell's current session. 'history -a' for viewing the global history of the shell's all sessions.",
    'head': "Displays the first 10 lines of a file by default. \nusage: 'head [FILE]' or 'head [FILE] -n [NUMBER_OF_LINES]'",
    'tail': "Displays the last 10 lines of a file by default. \nusage: 'tail [FILE]' or 'tail [FILE] -n [NUMBER_OF_LINES]'",
    'touch': "Creates an empty file if it does not exist. Changes the timestamps - Access and Modification times of the file to the current time if it already exists. \nusage: 'try touch [FILE]...'",
    'wc': "Displays the number of lines, word count, characters count in the file(s) specified as arguments. \nusage: 'wc [FILE]...'",
    'ip': "Displays the IP Address and other basic network details. \nusage: 'ip'",
    'host': "Displays the IP Address of the given domain. \nusage: 'host [DOMAIN]'",
    'arch': "Displays the machine's hardware details. \nusage: 'arch'",
    'ps': "Displays the snapshot of the current processes. \nusage: 'ps'",
    'wget': "Network downloader - download files from internet. \nusage: 'wget [URL]'",
    'kill': "Terminate an unresponsive program. \nusage: 'kill [PID]'",
    'diff': "Compares files line by line. \nusage: 'diff [FILE1] [FILE2]'",
    'grep': "Utility for searching plain-text data sets for lines that match a regular expression. \nusage: 'grep [expression] [data-set] -f' {if the data-set is a file}\nusage: 'grep [expression] [data-set]' {if the data-set is an input string}",
    'chmod': "Changes access permissions and the special mode flags of file system objects. \nusage: 'chmod [PERMISSIONS] [FILES]... --- Changes permissions of files and directories listed\nusage: chmod -c [PERMISSIONS] [FILES]... --- changes permissions of contents of directories listed as well'\nusage: chmod -C [PERMISSIONS] [FILES]... --- Changes permissions of contents of listed directories and its subdirectories as well",
    'tree': "Lists content of directories in tree like format. The current directory is listed by default if no directory path is provided. \nusage: 'tree' OR 'tree [DIRECTORY_PATH]'",
}
